theme: jekyll-theme-cayman
title: IT 4 Social Economy
description: IT Cooperatives inter-cooperating for a better future
links:
  website: http://it4socialeconomy.org/
  join: ./#join-us
  doc: http://doc.it4socialeconomy.org/